/**
 * Generated by `npm run images` — do not edit by hand.
 *
 * Describes what `scripts/build-images.mjs` wrote into `public/assets/img/`:
 * one AVIF and one WebP per width, plus a single `<name>.jpg` fallback.
 */
export interface ResponsiveImage {
  /** Basename shared by every derivative, e.g. `hero` -> `hero-1280.avif`. */
  name: string;
  /** Intrinsic widths available in the `srcset`, ascending. */
  widths: readonly number[];
  /** Intrinsic size of the JPEG fallback — carries the aspect ratio. */
  width: number;
  height: number;
}

export const IMAGES = {
  "forest": {
    "name": "hero",
    "widths": [
      640,
      960,
      1280,
      1600,
      1920,
      2560
    ],
    "width": 1600,
    "height": 1081
  },
  "portrait": {
    "name": "portrait",
    "widths": [
      384,
      512,
      768,
      1024,
      1536
    ],
    "width": 768,
    "height": 1152
  }
} as const satisfies Record<
  string,
  ResponsiveImage
>;
