/**
 * Non-translated site configuration: navigation targets, contact details,
 * social profiles and third-party scheduling links.
 *
 * Anything a visitor reads lives in `src/i18n/translations.ts`; this file only
 * holds the values that are identical in every language.
 */
import type { ResponsiveImage } from './images';

/**
 * Canonical origin and layout hints, re-exported from `src/site.config.ts`.
 *
 * They live there rather than here because `vite.config.ts` imports them too,
 * and this module reaches for `import.meta.env` — which does not exist while
 * Vite is loading its own config.
 */
export { SITE_URL, HERO_SIZES, PORTRAIT_SIZES } from '../site.config';

/** Service categories. These ids key the booking form, the pricing cards and
 *  the Cal.com scheduling links, so they must stay in sync across all three. */
export const SERVICE_CATEGORIES = ['individual', 'sports', 'parenting'] as const;

export type ServiceCategory = (typeof SERVICE_CATEGORIES)[number];

/**
 * Navigation targets. Every entry must correspond to a section `App` actually
 * renders — a link to a missing id silently does nothing when clicked.
 *
 * `testimonials` is commented out here for exactly that reason: `<Testimonials />`
 * is disabled in `App.tsx` until there is real content for it. Re-enable both
 * together.
 */
export const NAV_LINKS = [
  { key: 'about', href: '#about' },
  { key: 'services', href: '#services' },
  { key: 'pricing', href: '#pricing' },
  // { key: 'testimonials', href: '#testimonials' },
  { key: 'contact', href: '#booking' },
] as const;

/**
 * Section ids the navigation highlights while scrolling. Same rule as above,
 * plus one more: every id here must be reachable from `NAV_LINKS`, because
 * `Navbar` matches them by comparing `active === href.slice(1)`. The contact
 * link used to point at `#contact` — the footer — which meant the section it
 * scrolled past ('booking') could never light up the link.
 */
export const SECTION_IDS = ['about', 'services', 'pricing', 'booking'];

export type ContactChannel = 'phone' | 'email';

/**
 * Contact details, stored obfuscated so no literal address or number appears
 * in the bundle, the served HTML, or the DOM. They are decoded only inside the
 * click handler that reveals them — see `src/lib/contact.ts` for what this does
 * and does not protect against.
 *
 * Regenerate the payloads after changing any value:
 *   node scripts/encode-contact.mjs "<phone>" "<email>"
 *
 * TODO(launch): replace with Czárth Zsófia's real address and number — the
 * values below are development placeholders.
 */
export const CONTACT = {
  /** Must match the key the payloads were generated with. */
  key: 'czs-contact-v1',
  phone: {
    /** Shown before the visitor asks to see the real value. */
    mask: '+36 30 ••• ••••',
    payload: 'SElFDVRfTkZUUVQYRghR',
  },
  email: {
    mask: '•••••••••@gmail.com',
    payload: 'AAASXxcHQA4SDBJEFwFROhRAAgYCWgIMGQ==',
  },
} as const satisfies {
  key: string;
} & Record<ContactChannel, { mask: string; payload: string }>;

export const SOCIAL_LINKS = [
  { name: 'Instagram', href: 'https://www.instagram.com/psychologysophie/' },
  { name: 'Facebook', href: 'https://www.facebook.com/csengezsofia.czarth.3' },
  { name: 'LinkedIn', href: 'https://www.linkedin.com/in/czarthcsengezsofia/' },
] as const;

/**
 * Cal.com embed configuration.
 *
 * TODO(launch): these event types belong to the developer's Cal.com account.
 * Point them at the practice's own account before going live.
 */
export const CAL = {
  namespace: 'booking',
  brandColor: '#b85c3c',
  links: {
    parenting: 'zsofia-czarth-rohber/parent',
    individual: 'zsofia-czarth-rohber/normal',
    sports: 'zsofia-czarth-rohber/sport',
  } satisfies Record<ServiceCategory, string>,
} as const;

/** Resolves an asset in `public/` against Vite's configured base path. */
export function asset(path: string): string {
  return `${import.meta.env.BASE_URL}${path}`;
}

/**
 * Responsive photography.
 *
 * The camera originals live in `assets-src/` and are never deployed. The
 * manifest below is generated by `npm run images` alongside the files it
 * describes, so the widths here can never drift from the widths on disk.
 */
export { IMAGES } from './images';
export type { ResponsiveImage } from './images';

/** Builds the `srcset` for one format of a responsive image. */
export function srcSet(image: ResponsiveImage, format: 'avif' | 'webp'): string {
  return image.widths
    .map((w) => `${asset(`assets/img/${image.name}-${w}.${format}`)} ${w}w`)
    .join(', ');
}

/** The `<img src>` fallback every browser understands. */
export function fallbackSrc(image: ResponsiveImage): string {
  return asset(`assets/img/${image.name}.jpg`);
}

/**
 * Legal documents served straight from `public/`. Linked from the footer and
 * from the booking form's consent checkbox; both open them in a new tab so a
 * half-filled form is never lost.
 */
export const LEGAL_DOCS = {
  privacy: 'assets/Adatvedelem_CzarthZsofia.pdf',
  terms: 'assets/ASZF_CzarthZsofia.pdf',
} as const;
